
import React, { useEffect, useState } from 'react';
import { db } from '../db';
import { Bill, Expense, Settings } from '../types';
import { startOfDay, endOfDay, startOfWeek, endOfWeek, startOfMonth, endOfMonth, isWithinInterval, format } from 'date-fns';
import { TrendingUp, TrendingDown, DollarSign, Wallet, Share2, Download, FileSpreadsheet } from 'lucide-react';
import { exportToExcel, generateReportPDF } from '../utils/exportUtils';

const DashboardView: React.FC<{ settings: Settings }> = ({ settings }) => {
  const [bills, setBills] = useState<Bill[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [range, setRange] = useState<'daily' | 'weekly' | 'monthly'>('daily');

  useEffect(() => {
    const fetchData = async () => {
      const allBills = await db.bills.toArray();
      const allExpenses = await db.expenses.toArray();
      setBills(allBills);
      setExpenses(allExpenses);
    };
    fetchData();
  }, []);

  const getFilteredData = () => {
    const now = new Date();
    let interval: { start: Date; end: Date };

    if (range === 'daily') {
      interval = { start: startOfDay(now), end: endOfDay(now) };
    } else if (range === 'weekly') {
      interval = { start: startOfWeek(now), end: endOfWeek(now) };
    } else {
      interval = { start: startOfMonth(now), end: endOfMonth(now) };
    }

    const filteredBills = bills.filter(b => isWithinInterval(new Date(b.date), interval));
    const filteredExpenses = expenses.filter(e => isWithinInterval(new Date(e.date), interval));

    const totalSales = filteredBills.reduce((sum, b) => sum + b.total, 0);
    const totalExp = filteredExpenses.reduce((sum, e) => sum + e.amount, 0);
    const cashTotal = filteredBills.filter(b => b.paymentMode === 'Cash').reduce((sum, b) => sum + b.total, 0);
    const upiTotal = filteredBills.filter(b => b.paymentMode === 'UPI').reduce((sum, b) => sum + b.total, 0);

    return { totalSales, totalExp, profit: totalSales - totalExp, cashTotal, upiTotal };
  };

  const stats = getFilteredData();

  const sendWhatsAppSummary = () => {
    const text = `*Daily Sales Report - ${settings.shopName}*\n` +
      `Date: ${format(new Date(), 'dd/MM/yyyy')}\n` +
      `--------------------------\n` +
      `Total Sales: ₹${stats.totalSales.toFixed(2)}\n` +
      `Total Expenses: ₹${stats.totalExp.toFixed(2)}\n` +
      `Profit: ₹${stats.profit.toFixed(2)}\n` +
      `--------------------------\n` +
      `Cash: ₹${stats.cashTotal.toFixed(2)}\n` +
      `UPI: ₹${stats.upiTotal.toFixed(2)}\n` +
      `--------------------------\n` +
      `Generated by ShopBill Pro`;

    const encoded = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  };

  const handleExportPDF = () => {
    const reportData = [{
      'Report Period': range.toUpperCase(),
      'Total Sales': stats.totalSales,
      'Total Expenses': stats.totalExp,
      'Profit': stats.profit,
      'Cash Total': stats.cashTotal,
      'UPI Total': stats.upiTotal
    }];
    generateReportPDF(`${range.toUpperCase()} Sales Report`, reportData, settings);
  };

  const handleExportExcel = () => {
    const reportData = [{
      'Period': range.toUpperCase(),
      'Total Sales': stats.totalSales,
      'Total Expenses': stats.totalExp,
      'Net Profit': stats.profit,
      'Cash Payments': stats.cashTotal,
      'UPI Payments': stats.upiTotal
    }];
    exportToExcel(reportData, `${range}_report_${format(new Date(), 'yyyyMMdd')}`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <h2 className="text-2xl font-bold">Business Overview</h2>
        <div className="flex bg-white rounded-lg p-1 border shadow-sm">
          {(['daily', 'weekly', 'monthly'] as const).map(r => (
            <button
              key={r}
              onClick={() => setRange(r)}
              className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all ${range === r ? 'bg-indigo-600 text-white shadow' : 'text-slate-600 hover:text-slate-900'}`}
            >
              {r.charAt(0).toUpperCase() + r.slice(1)}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <StatCard title="Total Sales" value={stats.totalSales} icon={<TrendingUp className="text-emerald-500" />} color="bg-emerald-50" />
        <StatCard title="Total Expenses" value={stats.totalExp} icon={<TrendingDown className="text-rose-500" />} color="bg-rose-50" />
        <StatCard title="Net Profit" value={stats.profit} icon={<DollarSign className="text-indigo-500" />} color="bg-indigo-50" />
        <StatCard title="Cash Revenue" value={stats.cashTotal} icon={<Wallet className="text-amber-500" />} color="bg-amber-50" />
        <StatCard title="UPI Revenue" value={stats.upiTotal} icon={<Wallet className="text-sky-500" />} color="bg-sky-50" />
      </div>

      <div className="bg-white rounded-xl shadow-sm border p-6">
        <h3 className="text-lg font-semibold mb-4">Export & Share</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button onClick={handleExportPDF} className="flex items-center justify-center space-x-2 px-4 py-3 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg transition-colors font-medium">
            <Download size={20} />
            <span>Download PDF</span>
          </button>
          <button onClick={handleExportExcel} className="flex items-center justify-center space-x-2 px-4 py-3 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg transition-colors font-medium">
            <FileSpreadsheet size={20} />
            <span>Export Excel</span>
          </button>
          <button onClick={sendWhatsAppSummary} className="flex items-center justify-center space-x-2 px-4 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg transition-colors font-medium">
            <Share2 size={20} />
            <span>Send Daily Summary</span>
          </button>
        </div>
      </div>
    </div>
  );
};

const StatCard: React.FC<{ title: string; value: number; icon: React.ReactNode; color: string }> = ({ title, value, icon, color }) => (
  <div className="bg-white rounded-xl shadow-sm border p-6 flex items-start justify-between">
    <div>
      <p className="text-sm font-medium text-slate-500">{title}</p>
      <h3 className="text-2xl font-bold mt-1 text-slate-900">₹{value.toFixed(2)}</h3>
    </div>
    <div className={`p-3 rounded-lg ${color}`}>
      {icon}
    </div>
  </div>
);

export default DashboardView;
